### ISSUE TITLE
"The class name format is invalid." error when adding new model

### ISSUE THREAD

**Issue by codaha** [rainlab/builder-plugin#102]
Dont know if this is a problem with builder or october itself, but when i try to add new model with non-capital first letter i get this error:

"The class name format is invalid."

**Comment by gabsource** [comment]
The regular expression is `/^[a-zA-Z]+[0-9a-z\_]*$/`.
I got the same error using a model class name like `OAuth2Settings`.
I don't know if the class name restriction is due to some requirements or if the regex could be more permissive (uppercase letter in the second bracket) : `/^[a-zA-Z]+[0-9a-zA-Z\_]*$/`

**Comment by daftspunk** [comment]
If I remember correctly author names had to start with a capital letter. The reason escapes me at the moment. Class names shouldn't matter, perhaps the same rules are being applied.

**Comment by alekseybobkov** [comment]
Builder promotes the [PSR](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview) coding standards:

> Class names MUST be declared in StudlyCaps

Also, class names in PHP cannot start with a digit.
