### ISSUE TITLE
Unable to edit database build 365

### ISSUE THREAD

**Issue by jamiegrand** [rainlab/builder-plugin#104]
Unable to edit databases. problem with css in tabs something to do with class "oc-logo-transparent"

`<div data-control="tab" data-closable="" data-close-confirmation="Close the tab? Unsaved changes will be lost." data-pane-classes="layout-fill-container" data-max-title-symbols="15" data-title-as-file-names="false" class="flex-layout-column fill-container control-tabs master-tabs fancy-layout oc-logo-transparent has-tabs" id="builder-master-tabs">`

**Comment by canthis** [comment]
Just to make things a little bit clearer.

##### Expected behavior
Builder plugins _.tab-content_ section elements should be clickable
![Screenshot](http://i.imgur.com/hx1e4lt.jpg)


##### Actual behavior
![Screenshot](http://i.imgur.com/vgD5FcU.jpg)

_.tab-content_ div is being overlayed by pseudo-elements listed below
```
.fancy-layout.control-tabs.master-tabs.has-tabs:after {
    display: block;
}
```
and
```
.layout.control-tabs.oc-logo-transparent:not(.has-tabs):after, 
.layout-cell.oc-logo-transparent:after, 
.flex-layout-column.oc-logo-transparent:after {
    display: table-cell;
}
```

Removing _oc-logo-transparent_ class or setting _display: none;_ for elements listed above removes overlay and makes everything act like expected.

##### October build
356

**Comment by jamiegrand** [comment]
![screen](https://cloud.githubusercontent.com/assets/6545316/17521342/e1063a02-5e4a-11e6-8957-c6292d9d147c.jpg)

**Comment by canthis** [comment]
@jamiegrand This issue can be closed, cause it was alredy reported [here.](https://github.com/octobercms/october/commit/0b0e1580094f6ac19818b869b138a7e974115e3d) 
And commit, that broke those things has been already reverted by [#2293](https://github.com/octobercms/october/pull/2293)

**Comment by daftspunk** [comment]
Duplicate #2293
This will be fixed in the next build, sorry for the confusion. Build 357+
