### ISSUE TITLE
Model columns.yaml and fields.yaml not show form builder

### ISSUE THREAD

**Issue by ardani** [rainlab/builder-plugin#11]
After I click Models and create fields.yaml i not see form builder for generate fields form. 
screenshot :
http://prntscr.com/a1o41y

**Comment by alekseybobkov** [comment]
Please make sure that you're running the latest Build of October. 

1. Are there any JavaScript errors?
2. What browser you use?

**Comment by joebuonocore** [comment]
This happens to me too. Safari. I have this error in console:

Viewport argument key "minimal-ui" not recognized and ignored.

**Comment by alekseybobkov** [comment]
@joebuonocore:

* Are you running the latest October build? 
* What OS? Mac? Windows?
* Can you try another browser?

I can't replicate the problem in Safari, FireFox and Chrome with the latest builds of October and Builder.

**Comment by joebuonocore** [comment]
I narrowed down the problem to being caused by the styles I had overriding the october.css file in modules/backend/assets/css. That was my fault.

I'm concluding that @ardani was facing the same issue because he wasn't running build 316. Noticed once I removed my styles while running 316, everything rendered properly. Narrowed down the style issue, fixed and refreshed to find all working.

Thanks for looking out.
