### ISSUE TITLE
As i update plugin made by builder i lost data in the data table

### ISSUE THREAD

**Issue by shajidkhn26** [rainlab/builder-plugin#120]
Dear Team,
No doubt that builder plugin is awesome it helps creating plugin easily and fastly.But the only problem i am getting is that when i add new field in my table and use this command  "php artisan plugin:refresh Shajid.Zamzam" it reinstall my plugin and the data which are in the database completely gone out of tables.Is there any way by which i can update plugin without loosing data.Thank you

**Comment by daftspunk** [comment]
The plugin refresh command will always cause data loss because it calls the `down()` method in all the migrations, which deletes the tables. In this case when you add a new field you may simply need to run `php artisan october:up` to initiate the database migration process. Although this should happen already as part of the existing workflow to add a new field.

**Comment by shajidkhn26** [comment]
Thank you  i got it and it is done..
