### ISSUE TITLE
Session Lifetime

### ISSUE THREAD

**Issue by jamiegrand** [rainlab/builder-plugin#128]
setting the session lifetime in config to : 

 'lifetime' => 0,

will cause the following error 

![untitled-1](https://cloud.githubusercontent.com/assets/6545316/21186832/cf8a76e0-c20d-11e6-93cb-c9fa8ac8bc1e.jpg)

**Comment by alekseybobkov** [comment]
Many back-end widgets use the session for storing user preferences. For example, the search query in the page list in the CMS area. I think this should not be considered as a problem - you can set the session life time greater than zero in the development environment, because Builder is obviously a development tool and should not be used on a production server.
