### ISSUE TITLE
Duplicate column function

### ISSUE THREAD

**Issue by kubis** [rainlab/builder-plugin#132]
At creating tables there could be another helpful function "Duplicate column",  which would duplicate existing selected column, with all settings. After duplication is done, only the name of column have to be changed manually and you are ready for next column,

This would be a time saving function if you have 10+ columns which are basically more or less the same.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

Closing as it has been over a month since any activity on this occurred.
