### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by kutups** [rainlab/builder-plugin#223]
Hello, @LukeTowers 
It works very well, but. If we use more than one language, how do we do it?

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
