### ISSUE TITLE
error: "Form record with an ID of 1 could not be found."

### ISSUE THREAD

**Issue by songchidechet** [rainlab/builder-plugin#229]
I use Builder plugin to create my own plugin, in the list page, when I click Add new button and add first record to my plugin's table, then I click Create, it redirect to list page again and shows error "Form record with an ID of 1 could not be found." Please help

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
