### ISSUE TITLE
Can't add image field

### ISSUE THREAD

**Issue by ChristianGiupponi** [rainlab/builder-plugin#25]
I have tried to add an image upload file but when I try to visit the form I get:

~~~
We're sorry, but an unhandled error occurred. Please see the details below.

Model 'ZeroUnoSrl\Usato\Models\Usato' does not contain a definition for 'copertina'.
/home/vagrant/www/OctoberCMS/modules/backend/FormWidgets/FileUpload.php line 271
TYPE
~~~

I have added the `copertina` filed:

<img width="350" alt="schermata 2016-02-12 alle 10 42 31" src="https://cloud.githubusercontent.com/assets/1614796/13003338/61486c02-d175-11e5-9a9d-0585f9b5b9b6.png">

I have set the `copertina`field as `string`, is this the problem?

**Comment by pvullioud** [comment]
copertina is not a field of your table. it's a relation. You have to modify the model like this

```
    public $attachMany = [
        'copertina => ['System\Models\File','order' => 'sort_order']
    ];
```

**Comment by daftspunk** [comment]
Or for a single file upload

    public $attachOne = [
        'copertina => 'System\Models\File'
    ];

**Comment by alekseybobkov** [comment]
The Builder documentation is updated (see the **Managing back-end forms** section): http://octobercms.com/plugin/rainlab-builder. I added this section: 

> **Note:** some form controls, for example the file upload control, require a relation to be created in the model class manually. The relation name should be entered in the Field name property. Please read the [Forms Documentation](http://octobercms.com/docs/backend/forms) for details about specific form controls.

**Comment by ChristianGiupponi** [comment]
Thanks Guys!

**Comment by daslicht** [comment]
I have a similar issue, how do you get the File Path , please?

That's what I have so far :
https://github.com/JumpLinkNetwork/Downloads/blob/master/models/File.php#L30

**Comment by daslicht** [comment]
Solved myself , we don't need to define the file in Builder, attaching is enough

**Comment by dmitrybarchuk** [comment]
Hello, dalicht!
Can you tell me, what to do for working with attachments in Builder Plugin? I have field `image` in my table, i've made field Image in create/update form by using widget File upload (field name -> image). In my model i wrote:

"public $attachOne = [
     'image' => ['System\Models\File']
];"

File (image) uploading, but in my database fields're empty. I read about relations, but
firstly, don't know how to do it;
secondly, how can I choose destination folder for uploading files/images?

**Comment by bcatdc** [comment]
Hey Dmitry, 
I'm trying to get this working as well. Getting NULL in the database instead of a file path. I found at least part of the answer to where to store files. /config/cms.php under the heading Resource Storage. Looks like you can set up preferences there. 

Would love a more detailed tutorial on this. I'm a little new to frameworks and thinking in the MVC mindset, but I'm banging my head against this problem.

**Comment by daslicht** [comment]
I apologize for the late reply, but I was quite busy here , but finally I have some time :)

Thats the solution I found, probably that helps somehow.
https://github.com/JumpLinkNetwork/Downloads

I haven't continue working on this since we followed a different Download approach where the client just uploads the Files in the Theme settings:

https://github.com/JumpLinkNetwork/DownloadBundle
