### ISSUE TITLE
Issue in localization

### ISSUE THREAD

**Issue by suraj2209** [rainlab/builder-plugin#268]
Hello Everyone i am using builder Plugin and it works fine but i am getting a issue related to localization. I have created a CRUD and i am creating and displaying that data on a page now i want to use localization in it so how can i do so

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
