### ISSUE TITLE
Builder Plugin does not work with multi-line update messages

### ISSUE THREAD

**Issue by GinoPane** [rainlab/builder-plugin#284]
Some time ago if implemented support of multi-line update messages for October, but I had no idea that the Builder plugin heavily relies on the old structure (I just didn't use it before).

But now I have faced the issue, that the Builder treats every message after the first one as file: 
![image](https://user-images.githubusercontent.com/3897579/59375925-d400bc80-8d57-11e9-855b-5b19905a5781.png)

And moreover it does not support multiple files (this limitation existed before):

![image](https://user-images.githubusercontent.com/3897579/59375990-f09cf480-8d57-11e9-9c2f-7a8a6a3ee117.png)

**Comment by LukeTowers** [comment]
@GinoPane feel free to make a PR to fix support for this, although I don't know how successful you'd be at adding support for editing versions with multiple PHP scripts

**Comment by GinoPane** [comment]
@LukeTowers it's a good question :) I was surprised that multiple update scripts were not supported before.

**Comment by daftspunk** [comment]
Hi @GinoPane 

> multi-line update messages for October

This is never really a sanctioned feature because of problems it creates (like this one). It isn't used officially or documented anywhere, the system simply ignores non-script messages internally -- so it is possible for the developer to fill this space with a changelog, although it scales poorly.

The feature is intended to be a "version note" instead of a complete changelog. It is suggested to manage a separate changelog.txt file for this purpose.

The builder expects a specific syntax and isn't fully compatible with the October spec. We are planning on fixing this in the next major iteration of this plugin.

I hope this offers some clarity.
