### ISSUE TITLE
How to include power seo

### ISSUE THREAD

**Issue by bionner** [rainlab/builder-plugin#285]
I built a plugin with 8 records, but now i want to add the seo tags. I dont know how to do it, Is an approach available?

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
