### ISSUE TITLE
I can't connect images

### ISSUE THREAD

**Issue by Marysa123** [rainlab/builder-plugin#345]
Hello, I ran into a problem,I connect the image in this way `<li style= "background-image: url( {{ record.imagefon|media }});" >` but still gives an error 404 file not found although I go to the path that is specified it is there.I'm new to using October so I'm asking for help.

**Comment by bennothommo** [comment]
GitHub issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
Discord: https://discord.gg/6S777kh
