### ISSUE TITLE
Migration creation unstable

### ISSUE THREAD

**Issue by trsh** [rainlab/builder-plugin#82]
I got and error "to long index" when creating a table in builder, in result:

a) Table was created, without index.
b) Migration script was not present.

Expected result:

When something goes wrong in migration, no table should be created until the responsible script is fixed (by hand or in builder) - There should be and commit on all success and full rollback on fail. And the fallowing update scripts should not be executed. Otherwise when some script is missing, the whole migrations sequence is doomed.

**Comment by alekseybobkov** [comment]
There's a rollback feature, but it looks like it fails in your key. We will check it.

**Comment by alekseybobkov** [comment]
Full automatic rollback when a migration fails due to a runtime error (unexpected database structure, etc.) is not possible if the migration contains multiple operations. For example, if there're 3 operations in the `up()` method, and the second one failed, the `down()` method would try to execute the rollback code for all three operations and would fail as well (because only one operation in `up()` succeeded).

We can try to prevent some problems automatically (like the "identifier name is too long", reported in #64), but even those checks can fail, because requirements and limitations are different across database engines supported by Eloquent and because we can't predict all possible issues. Some manual work will always be required when you use Builder (or any other tool).
