### ISSUE TITLE
Philosophy Question: Protoyping in OctoberCMS

### ISSUE THREAD

**Issue by lionax** [rainlab/builder-plugin#89]
As in #21 and the Docs of this Plugin you are focusing on the CMS part of October. Still the ability to use the builder plugin effectively for prototyping of plugins (works great already but could yet be improved) and hence for applications based on October.

From the view of a scientist but also as a coder in research facilities I see great potential in this philosophy.

I also wrote a first intro article on [a blog](https://www.shivering-isles.com/consider-app-prototyping-in-october/) to put this on discussion. What do you think?

**Comment by alekseybobkov** [comment]
@lionax - thanks for the blog post. I don't have much input about the post contents. It looks correct to me. Many bugs have been fixed since you published the post. Regarding the issue that you mentioned:

> Delete Button of Controllers is missing, so you have to delete them with the editor.

This is done intentionally and mentioned in the [Builder documentation](http://octobercms.com/plugin/rainlab-builder):

> Builder is a productivity tool, it doesn't completely replace coding by hand and doesn't include a code editor for editing PHP files (the only exception is the version management interface). Builder never overwrites or deletes plugin PHP files, so you can rest assured knowing that the code you write never gets touched by Builder. However, Builder can create new PHP files, like models and controllers.

Please use the issue tracker only for [requesting specific features or reporting bugs](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md).
