### ISSUE TITLE
Reorder things

### ISSUE THREAD

**Issue by Zmove** [rainlab/builder-plugin#99]
Hello,

I don't see any options to reorder fields in the database or columns in the model/columns.yaml

Would it be possible to add drag & drop reordering functionnality in the UI ?

Best regards, and continue that great work !

**Comment by LittleTom** [comment]
My English is not very well,I hope to help you at here.
This feature doesn't seem to be completely finished.
If you want to get the job done, you can follow me to have a try.
====================================================
First, the Model class need add this code.
`use \October\Rain\Database\Traits\NestedTree;
`
====================================================
Next,this Model's datebase table need add 4 COLUMNs,like this:
   COLUMN    TYPE   LENGTH
  parent_id     int      10
  nest_left      int       11
  nest_right    int      11
  nest_depth  int      11
====================================================
And then,add reorder button in "YourPlugin /controllers/categories/_list_toolbar.htm",like this:
`<a href="<?= Backend::url('YourNameSpace/blog/categories/reorder') ?>" class="btn btn-default oc-icon-sitemap">
        reorder list
</a>`
Note that you need to modify yourself path.
====================================================
At last,add code in this file's end:"YourPlugin /controllers/YourFile/config_list.yaml"
`showTree: true`

**Comment by alekseybobkov** [comment]
I don't think that this sophisticated column management will ever be implemented in Builder. I'm marking this issue as accepted, but low priority.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

Closing as it has been over a month since any activity on this occurred.
